spring.application.name=RegistrationSys

# H2 In-Memory DB
spring.datasource.url=jdbc:h2:file:./data/testdb

spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#Email config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ahmedzayed1337@gmail.com
spring.mail.password=rvzk mvgw glth tcuy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


#Redis-server
#spring.data.redis.host=localhost
#spring.data.redis.port=6379
#spring.data.redis.timeout=60000


